name: Build Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup .NET (with NuGet cache)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/packages.lock.json
            **/nuget.config

      - name: Restore dependencies
        run: dotnet restore StrmAssistant/StrmAssistant.csproj

      - name: Build the project
        run: dotnet build StrmAssistant/StrmAssistant.csproj --no-restore --configuration Release -p:UseSharedCompilation=false

      - name: List build output
        run: ls -R StrmAssistant/bin/Release || true

      - name: Upload artifact (build output)
        uses: actions/upload-artifact@v4
        with:
          name: StrmAssistantLite-${{ github.run_number }}
          path: StrmAssistant/bin/Release/**
          compression-level: 0
          retention-days: 30
